spring.application.name=blockchain-node
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n
spring.jackson.serialization.indent_output=true
#log requests
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

#logging.level.org.springframework.validation=DEBUG
#logging.level.org.hibernate.validator=DEBUG

