server.port=8081
spring.application.name=blockchain-node
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n
spring.jackson.serialization.indent_output=true
#log requests
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#logging.level.org.springframework.validation=DEBUG
#logging.level.org.hibernate.validator=DEBUG
genesis.data=/home/enruxer/_project_data/blockchain.genesis.json
miner.data=miner.json
init.users.data=users.json
storage.blocks.data=/home/enruxer/_project_data/blockchain.genesis.json
storage.users.data=/tmp/out-storage/users.json
