server.port=8082
node.url=http://localhost:8081
spring.application.name=blockchain-wallet
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{0} - %msg%n
spring.jackson.serialization.indent_output=true
#log requests
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#logging.level.org.springframework.validation=DEBUG
#logging.level.org.hibernate.validator=DEBUG
genesis.data=genesis.json
miner.data=miner.json
init.users.data=users.json
storage.blocks.data=/tmp/out-storage/blocks.json
storage.users.data=/tmp/out-storage/users.json

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-ui

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

wallet.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
wallet.app.jwtExpirationMs=864000000

logging.level.org.springframework.security=DEBUG

#spring.security.enabled=false

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
#Disable caching for development
spring.thymeleaf.cache=false
